### ISSUE TITLE
Crash in mn-samples-itu `STL-manual.adoc`

### ISSUE THREAD

**Issue by ronaldtse** [plurimath/plurimath#125]
From: https://github.com/metanorma/metanorma-itu/issues/422#issuecomment-1506157836

This formula in latexmath seems to cause a crash (note there are prefixing spaces:
```
    hanning(k)=0.5\cdot [1-\cos(2\pi \cdot \frac{k+1}{n+1})] \mbox{\rule{15mm}{0mm}} (0 \le k \le n-1)
```

However when I tried this in latest `main` there is no crash.

```ruby
> Plurimath::Math.parse('    \text{hanning}(k)=0.5\cdot [1-\cos(2\pi \cdot \frac{k+1}{n+1})] \mbox{
\rule{15mm}{0mm}} (0 \le k \le n-1)', :latex).to_mathml
=> "\n<math xmlns=\"http://www.w3.org/1998/Math/MathML\" display=\"block\">\n  <mstyle displaystyle=\"true\">\n    <mtext>hanning</mtext>\n    <mo>(</mo>\n    <mi>k</mi>\n    <mo>)</mo>\n    <mo>=</mo>\n    <mn>0</mn>\n    <mo>&#xb7;</mo>\n    <mn>5</mn>\n    <mo>&#x22c5;</mo>\n    <mo>[</mo>\n    <mn>1</mn>\n    <mo>&#x2212;</mo>\n    <mrow>\n      <mi>cos</mi>\n      <mo>(</mo>\n    </mrow>\n    <mn>2</mn>\n    <mi>&#x3c0;</mi>\n    <mo>&#x22c5;</mo>\n    <mfrac>\n      <mrow>\n        <mi>k</mi>\n        <mo>+</mo>\n        <mn>1</mn>\n      </mrow>\n      <mrow>\n        <mi>n</mi>\n        <mo>+</mo>\n        <mn>1</mn>\n      </mrow>\n    </mfrac>\n    <mo>)</mo>\n    <mo>]</mo>\n    <mtext>\n      <mi/>\n    </mtext>\n    <mo>(</mo>\n    <mn>0</mn>\n    <mo>&#x2264;</mo>\n    <mi>k</mi>\n    <mo>&#x2264;</mo>\n    <mi>n</mi>\n    <mo>&#x2212;</mo>\n    <mn>1</mn>\n    <mo>)</mo>\n  </mstyle>\n</math>\n"
```

**Comment by suleman-uzair** [comment]
Plurimath won't crash in the main branch since you merged [PR#124](https://github.com/plurimath/plurimath/pull/124) into the main, which had the fix in it.
And I have just released the gem's new version.

**Comment by ronaldtse** [comment]
Thank you @suleman-uzair !

Ping @opoudjis

**Comment by opoudjis** [comment]
The error is still there, but it occurs not on Latex > MathML, but on me round-tripping MathML, to confirm that the MathML is valid:

````
l = "    hanning(k)=0.5\\cdot [1-\\cos(2\\pi \\cdot \\frac{k+1}{n+1})] \\mbox{\\rule{15mm}{0mm}} (0 \\le k \\le
 n-1)"
a = Plurimath::Math.parse(l1, "latex").to_mathml # works fine, as above
Plurimath::Math.parse(a, "mathml") # is still OK
Plurimath::Math.parse(a, "mathml").to_mathml #crashes
````

You might argue that me doing `Plurimath::Math.parse(a, "mathml").to_mathml` on all MathML in the document is over-scrupulous. I... don't agree yet. :)

**Comment by ronaldtse** [comment]
So there are 2 potential problems here:

1. The MathML generated from this LaTeX math formula is wonky, which will crash the MathML round-trip
2. There is a MathML parsing issue, where a MathML round-trip crashes.

@suleman-uzair can you please help fix this ASAP? Thanks.

**Comment by suleman-uzair** [comment]
@ronaldtse This issue is already fixed in this PR #120.

**Comment by ronaldtse** [comment]
Thanks, #120 is now merged.

Ping @opoudjis that this issue is now resolved (once the new version is released)
